#!/bin/sh

# This script install jupyter notebook extensions through conda
# Requirement: conda

echo Installing Jupyter notebook extensions...
conda install -y -c conda-forge jupyter_contrib_nbextensions

echo Installing NbExtensions Configurator...
conda install -y -c conda-forge jupyter_nbextensions_configurator


echo Updating ipython_config.py...

echo 'c = get_config()

# Run all nodes interactively
c.InteractiveShell.ast_node_interactivity = "all"' >> ~/.ipython/profile_default/ipython_config.py

